### ISSUE TITLE
Everyone put your understanding of requirements 

### ISSUE THREAD

**Issue by KurtSome** [KurtSome/2020-GPW-L5K2-E#3]
Sales Information system:
      1. 10 bus routes at least.
      2. Easy to find and sell. (Functional)
      3. User can choose start station and end destination.
      4. Tickets level. (economy/business)
      5. One user-----one ticket. (Same time)
      6. Customer can buy meal in train. (Consideration range)
      7. Identification information for each ticket.
      8. Different payment methods.
      9. Costs function. (Discount)

Management Information System
      1. List of all tickets sold on a specific day.
      2. Report chart.
      3. Dashboard: Amount of tickets sold.
                               Daily revenue
                               Most popular destination
                               Anual incoming
      4. Manager must be able to see an ordered list of which traveler spend the most money on bus
tickets in a specific month

**Comment by iamjamessen** [comment]
[Product Backlog For China Railway System.pdf](https://github.com/KurtSome/2020-GPW-L5K2-E/files/4569797/Product.Backlog.For.China.Railway.System.pdf)

**Comment by iamjamessen** [comment]
[Product Backlog For CBS.pdf](https://github.com/KurtSome/2020-GPW-L5K2-E/files/4569818/Product.Backlog.For.CBS.pdf)

**Comment by iamjamessen** [comment]
[requirements for CBS.pdf](https://github.com/KurtSome/2020-GPW-L5K2-E/files/4569862/requirements.for.CBS.pdf)
