### ISSUE TITLE
Create the first version of database.

### ISSUE THREAD

**Issue by KurtSome** [KurtSome/2020-GPW-L5K2-E#9]

**Comment by KurtSome** [comment]
I redesign the customer information system's ERD.
![IMG_6202](https://user-images.githubusercontent.com/45254780/80933178-2544ef00-8df5-11ea-929b-eb20b577e501.jpg)

**Comment by KurtSome** [comment]
Improved
![IMG_6203](https://user-images.githubusercontent.com/45254780/80933911-49ee9600-8df8-11ea-951f-c53f85231771.jpg)

**Comment by KurtSome** [comment]
<img width="561" alt="屏幕快照 2020-05-04 20 45 35" src="https://user-images.githubusercontent.com/45254780/80967740-6ff05680-8e49-11ea-81ee-f9379a793b26.png">

**Comment by iamjamessen** [comment]
![bus-db](https://user-images.githubusercontent.com/48249915/81079610-553de080-8f22-11ea-9a17-78083bd5bb98.png)
